import { Red_Hat_Display } from "next/font/google";
import Footer from "@/components/Layouts/Footer";
import Header from "@/components/Layouts/Header";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import ReduxProvider from "@/components/reduxProvider";
import ClientLayout from "@/components/ClientLayout";
import WebEngageProvider from "@/components/WebEngageProvider";

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-red-hat",
});


export const metadata = {
  title: "Fintoo",
  description: "Generated by create next app",
  icons: {
    icon: "https://static.fintoo.in/static/userflow/img/favicon.ico",
  },
};

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body>
        <ReduxProvider>
          <ClientLayout>
              {children}
          </ClientLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
