import { Red_Hat_Display } from "next/font/google";
import Footer from "@/components/Layouts/Footer";
import "./globals.css";
    import 'bootstrap/dist/css/bootstrap.min.css';

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
  variable: "--font-red-hat",           // optional: custom CSS variable
});

export const metadata = {
  title: "Fintoo",
  description: "Generated by create next app",
   icons: {
    icon: "https://static.fintoo.in/static/userflow/img/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <main>{children}</main>  
          <Footer />
      </body>
    </html>
  );
}
