import { Red_Hat_Display } from "next/font/google";
import Footer from "@/components/Layouts/Footer";
import "./globals.css";
    import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/Layouts/Header";
import Head from "next/head";

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
  variable: "--font-red-hat",           // optional: custom CSS variable
});

export const metadata = {
  title: "Fintoo",
  description: "Generated by create next app",
   icons: {
    icon: "https://static.fintoo.in/static/userflow/img/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
       <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>

      </Head>
      <body >
        <Header/>
        <main>{children}</main>  
          <Footer />
      </body>
    </html>
  );
}
